version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatdb
    networks:
      - chatbot_network
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  
  sparql_generator:
    build:
      context: .
      dockerfile: Dockerfile.sparql_gen_benchmark
    container_name: chatbot-sparql_gen_benchmark
    ports:
      - "8502:8502"
    env_file:
      - ./sparql_gen_benchmark/.env
    networks:
      - chatbot_network
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: chatbot-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/chatdb
      - NVIDIA_VISIBLE_DEVICES=all  # すべてのGPUを表示
      - NVIDIA_DRIVER_CAPABILITIES=all  # すべてのドライバー機能を有効化
    networks:
      - chatbot_network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all   # すべてのGPUを使用する場合
              capabilities: [gpu]  # GPU機能を有効化

  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - db
    environment:
      - ADMINER_DESIGN=pepa-linha-dark
    ports:
      - "8080:8080"

networks:
  chatbot_network:
    driver: bridge

volumes:
  postgres_data:
